### ISSUE TITLE
Should we implement RF API?

### ISSUE THREAD

**Issue by Pannoniae** [CottonMC/UnitedManufacturing#1]
I'm leaning to the side of implementing it. I get, powercreep and yadda, but I think that would be a good catching point (and after we've done that, we can make "unofficial" extensions to it, making it less powercreepy)

What do you think? ;)

**Comment by LemmaEOF** [comment]
RF isn't on Fabric, so there's no point. We have Cotton Energy and it's just fine.

**Comment by Pannoniae** [comment]
A set of interfaces is *not* modloader-dependent. Am I missing something?

**Comment by LemmaEOF** [comment]
Two things: names and Fabric loading it. We don't have the right to port RF; it's ARR. The Forge version isn't compatible with Fabric, so we can't use it.

**Comment by Pannoniae** [comment]
Or, alternatively we can ask. Doesn't hurt anyone.

**Comment by LemmaEOF** [comment]
If you wanna try and convince one of the head contributors of Forge to switch mod loaders, be my guest. I'm not gonna do it.

**Comment by Pannoniae** [comment]
Is this some sort of "whose modloader is better?" competition? There is no forge 1.14.

**Comment by LemmaEOF** [comment]
No, I'm saying it's not worth the effort because Lemming is already strongly invested in Forge. He's not gonna give up that sunk cost to work on something he's already publicly criticized.

**Comment by falkreon** [comment]
Even if there's an RF-API port, I wouldn't use it. Look at TechReborn's implementation of IC2-Experimental's features on top of forge energy. The port is super faithful, but it feels terrible because it's a terrible fit for the mod.
