### ISSUE TITLE
Add textures for machines

### ISSUE THREAD

**Issue by falseresync** [CottonMC/UnitedManufacturing#2]
Textures:
- [x] Coal Generator
- [x] Hammer Mill
- [ ] Die Cutter
- [ ] Extractor
- [ ] Roller

**Comment by Bluberry-Kat** [comment]
updated coal generator texture in a0236b1
rework for other textures pending, looking for feedback

**Comment by falkreon** [comment]
Right now anything on a machine that isn't the conveyors, generator, conduits, or hammer mill is low priority. That said, we certainly could use more eyeballs on the ones I just listed.
